import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import ReactMarkdown from 'react-markdown';
import { 
  Bot, 
  Sparkles, 
  MoveRight, 
  Loader2, 
  ArrowRight, 
  Activity, 
  GitMerge, 
  FileText,
  ShieldCheck,
  Send,
  Image as ImageIcon,
  X,
  Mic,
  MicOff,
  Twitter,
  Facebook,
  Linkedin,
  MessageCircle,
  Copy
} from 'lucide-react';
import { generateInitialSolution, verifyAndOptimize } from './lib/gemini';
import { cn } from './lib/utils';

type ProcessState = 'idle' | 'primary' | 'twin' | 'completed' | 'error';
type ActiveTab = 'primary' | 'critique' | 'final';

export default function App() {
  const [prompt, setPrompt] = useState('');
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [status, setStatus] = useState<ProcessState>('idle');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<ActiveTab>('final');

  // Results
  const [primaryOutput, setPrimaryOutput] = useState('');
  const [critique, setCritique] = useState('');
  const [finalOutput, setFinalOutput] = useState('');
  const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);

  const [hasRun, setHasRun] = useState(false);
  const [generateImage, setGenerateImage] = useState(true);
  const [isReplaying, setIsReplaying] = useState(false);

  const replayEvolution = async () => {
    if (isReplaying) return;
    setIsReplaying(true);
    
    // Step 1: Initial Draft
    setActiveTab('primary');
    await new Promise(r => setTimeout(r, 2000));
    
    if (!isReplaying) return; // Note: state might be stale in closure, but we can just let it run.
    
    // Step 2: Critique
    setActiveTab('critique');
    await new Promise(r => setTimeout(r, 2000));

    // Step 3: Final Output
    setActiveTab('final');
    setIsReplaying(false);
  };

  const [isRecording, setIsRecording] = useState(false);
  const recognitionRef = useRef<any>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const toggleRecording = () => {
    if (isRecording) {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
      }
      setIsRecording(false);
      return;
    }

    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert('Speech recognition is not supported in this browser. Please try Chrome or Edge.');
      return;
    }

    const recognition = new SpeechRecognition();
    recognition.continuous = true;
    recognition.interimResults = false;
    
    recognition.onresult = (event: any) => {
      let finalTranscript = '';
      for (let i = event.resultIndex; i < event.results.length; ++i) {
        if (event.results[i].isFinal) {
          finalTranscript += event.results[i][0].transcript;
        }
      }
      if (finalTranscript) {
        setPrompt((prev) => prev + (prev.endsWith(' ') || prev === '' ? '' : ' ') + finalTranscript);
      }
    };

    recognition.onerror = (event: any) => {
      console.error('Speech recognition error:', event.error);
      setIsRecording(false);
    };

    recognition.onend = () => {
      setIsRecording(false);
    };

    recognition.start();
    recognitionRef.current = recognition;
    setIsRecording(true);
  };

  useEffect(() => {
    return () => {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
      }
    };
  }, []);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setImageFile(file);
      setPreviewUrl(URL.createObjectURL(file));
      // Reset input value so same file can be selected again
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  };

  const removeImage = () => {
    setImageFile(null);
    setPreviewUrl(null);
  };

  const handleShare = (platform: string) => {
    if (!finalOutput) return;
    const textToShare = finalOutput;
    const truncatedText = textToShare.length > 250 ? textToShare.substring(0, 250) + "..." : textToShare;
    const urlToShare = window.location.href; 
    
    let shareUrl = "";
    switch (platform) {
      case 'twitter':
        shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent("Generated by Twin Agent System:\n\n" + truncatedText)}`;
        break;
      case 'facebook':
        shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(urlToShare)}&quote=${encodeURIComponent(truncatedText)}`;
        break;
      case 'linkedin':
        shareUrl = `https://www.linkedin.com/shareArticle?mini=true&url=${encodeURIComponent(urlToShare)}&summary=${encodeURIComponent(truncatedText)}&title=Twin%20Agent%20Output`;
        break;
      case 'whatsapp':
        shareUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent("Check what I generated using the Twin Agent System:\n\n" + textToShare)}`;
        break;
    }
    
    if (shareUrl) {
       window.open(shareUrl, '_blank', 'noopener,noreferrer');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim() && !imageFile) return;

    setHasRun(true);
    setStatus('primary');
    setErrorMsg(null);
    setPrimaryOutput('');
    setCritique('');
    setFinalOutput('');
    setGeneratedImageUrl(null);
    setActiveTab('primary');

    try {
      let imagePart = undefined;
      if (imageFile) {
        const reader = new FileReader();
        const base64Data = await new Promise<string>((resolve) => {
          reader.onloadend = () => {
            const result = reader.result as string;
            resolve(result.split(',')[1]);
          };
          reader.readAsDataURL(imageFile);
        });
        imagePart = {
          inlineData: {
            data: base64Data,
            mimeType: imageFile.type
          }
        };
      }

      // Step 1: Primary Agent
      const primaryRes = await generateInitialSolution(prompt, imagePart);
      setPrimaryOutput(primaryRes);
      
      // Step 2: Twin Agent Verify & Optimize
      setStatus('twin');
      setActiveTab('critique');
      
      const twinRes = await verifyAndOptimize(prompt, primaryRes, imagePart, generateImage);
      setCritique(twinRes.critique);
      setFinalOutput(twinRes.optimizedContent);
      setGeneratedImageUrl(twinRes.generatedImageUrl ?? null);
      
      setStatus('completed');
      setActiveTab('final');

    } catch (err: any) {
      console.error(err);
      setStatus('error');
      setErrorMsg(err.message || 'An error occurred during processing.');
    }
  };

  const getStatusIcon = (step: 'primary' | 'twin' | 'completed') => {
    if (status === 'error') {
      return <div className="w-8 h-8 rounded-full glass bg-red-900/30 text-red-500 flex items-center justify-center border-red-500/20"><Activity size={14} /></div>;
    }
    if (status === 'idle') {
      return <div className="w-8 h-8 rounded-full glass text-slate-600 flex items-center justify-center border-white/10"><div className="w-2 h-2 rounded-full bg-slate-700" /></div>;
    }

    if (step === 'primary') {
      if (status === 'primary') return <div className="w-8 h-8 rounded-full glass bg-blue-500/20 text-blue-400 flex items-center justify-center border border-blue-500/30 animate-pulse"><Loader2 size={14} className="animate-spin" /></div>;
      return <div className="w-8 h-8 rounded-full glass bg-blue-900/30 text-blue-400 flex items-center justify-center border border-blue-500/20"><ShieldCheck size={14} /></div>;
    }
    
    if (step === 'twin') {
      if (status === 'primary') return <div className="w-8 h-8 rounded-full glass text-slate-600 flex items-center justify-center border border-white/10"><div className="w-2 h-2 rounded-full bg-slate-700" /></div>;
      if (status === 'twin') return <div className="w-8 h-8 rounded-full glass bg-purple-500/20 text-purple-400 flex items-center justify-center border border-purple-500/30 animate-pulse"><Loader2 size={14} className="animate-spin" /></div>;
      return <div className="w-8 h-8 rounded-full glass bg-purple-900/30 text-purple-400 flex items-center justify-center border border-purple-500/20"><ShieldCheck size={14} /></div>;
    }

    if (step === 'completed') {
      if (status === 'completed') return <div className="w-8 h-8 rounded-full glass bg-green-500/20 text-green-400 flex items-center justify-center border border-green-500/30"><Sparkles size={14} /></div>;
      return <div className="w-8 h-8 rounded-full glass text-slate-600 flex items-center justify-center border border-white/10"><div className="w-2 h-2 rounded-full bg-slate-700" /></div>;
    }
  };

  return (
    <div className="min-h-screen md:h-screen mesh-gradient text-slate-200 flex flex-col md:flex-row md:overflow-hidden font-sans relative">
      
      {/* LEFT PANEL: Input & Process Flow */}
      <div className="w-full md:w-[400px] lg:w-[450px] flex flex-col md:min-h-0 shrink-0 glass m-4 md:m-6 md:mr-3 rounded-2xl z-10 md:h-[calc(100vh-3rem)]">
        <div className="p-6 border-b border-white/10">
          <h1 className="text-xl font-light tracking-[0.2em] uppercase text-white mb-2 flex items-center gap-2">
            <GitMerge className="text-blue-400" />
            Twin <span className="text-blue-400 font-bold">Agent</span>
          </h1>
          <p className="text-[10px] text-slate-500 tracking-widest uppercase mt-1 leading-relaxed">
            Protocol: Dual-Intelligence Verification System
          </p>
        </div>

        <div className="p-6 flex-1 overflow-y-auto overflow-x-hidden relative">
          <form onSubmit={handleSubmit} className="mb-10 w-full relative z-10">
            <label className="block text-[10px] font-bold text-blue-400 uppercase tracking-tighter mb-3">
              Task Prompt
            </label>
            <textarea
              className="w-full glass bg-black/20 rounded-xl p-4 text-xs leading-relaxed text-gray-200 focus:outline-none focus:border-blue-400/50 transition-all resize-none"
              rows={5}
              placeholder="E.g., Write a creative short story about a time traveler who accidentally prevents the invention of coffee..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              disabled={status === 'primary' || status === 'twin'}
            />
            <div className="flex items-center gap-3 mt-4">
              <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileChange}
                accept="image/*"
                className="hidden"
              />
              <button
                type="button"
                onClick={toggleRecording}
                disabled={status === 'primary' || status === 'twin'}
                className={cn(
                  "w-12 h-12 rounded-lg glass border transition-all flex items-center justify-center shrink-0 group relative disabled:opacity-50",
                  isRecording 
                    ? "bg-red-500/20 text-red-500 border-red-500/50 shadow-[0_0_15px_rgba(239,68,68,0.2)]" 
                    : "bg-white/5 border-white/10 hover:bg-white/10 text-blue-400"
                )}
                title={isRecording ? "Stop recording" : "Start recording"}
              >
                {isRecording ? (
                  <>
                    <span className="absolute w-full h-full rounded-lg animate-ping bg-red-500/20" />
                    <MicOff size={20} className="relative z-10" />
                  </>
                ) : (
                  <Mic size={20} className="group-hover:scale-110 transition-transform" />
                )}
              </button>
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                disabled={status === 'primary' || status === 'twin'}
                className="w-12 h-12 rounded-lg glass bg-white/5 border border-white/10 hover:bg-white/10 flex items-center justify-center transition-all disabled:opacity-50 text-blue-400 group shrink-0"
                title="Upload image"
              >
                <ImageIcon size={20} className="group-hover:scale-110 transition-transform" />
              </button>
              
              <button
                type="submit"
                disabled={(!prompt.trim() && !imageFile) || status === 'primary' || status === 'twin'}
                className="flex-1 py-0 h-12 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-[10px] font-bold uppercase tracking-widest transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {(status === 'primary' || status === 'twin') ? (
                  <><Loader2 className="animate-spin" size={14} /> Processing...</>
                ) : (
                  <>Execute & Implement <Send size={14} /></>
                )}
              </button>
            </div>
            
            {previewUrl && (
              <div className="mt-4 relative inline-block">
                <img src={previewUrl} alt="Preview" className="h-20 w-auto rounded-lg border border-white/10" />
                <button
                  type="button"
                  onClick={removeImage}
                  disabled={status === 'primary' || status === 'twin'}
                  className="absolute -top-2 -right-2 w-5 h-5 rounded-full bg-red-500 text-white flex items-center justify-center hover:bg-red-400 transition-colors disabled:opacity-50"
                >
                  <X size={12} />
                </button>
              </div>
            )}
            
            <div className="mt-4 flex items-center justify-between border-t border-white/5 pt-4">
              <label className="flex items-center gap-2 cursor-pointer group">
                <div className="relative flex items-center justify-center w-4 h-4">
                  <input
                    type="checkbox"
                    checked={generateImage}
                    onChange={(e) => setGenerateImage(e.target.checked)}
                    disabled={status === 'primary' || status === 'twin'}
                    className="peer appearance-none w-4 h-4 rounded-[4px] border border-white/20 bg-black/20 checked:bg-blue-500 checked:border-blue-500 transition-all cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                  />
                  <ImageIcon size={10} className="absolute text-white opacity-0 peer-checked:opacity-100 peer-checked:scale-100 scale-50 transition-all pointer-events-none" />
                </div>
                <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest group-hover:text-slate-300 transition-colors">
                  Auto-Illustrate Output
                </span>
              </label>
            </div>
          </form>

          {/* Timeline visualization */}
          <div className="relative pl-4 space-y-8 z-0">
            {/* Thread line */}
            <div className="absolute left-[31px] top-[16px] bottom-[16px] w-[1px] bg-gradient-to-b from-blue-500/50 via-purple-500/20 to-transparent z-[-1]" />

            {/* Step 1: Primary Agent */}
            <div className={cn("relative z-10 flex gap-4 transition-opacity duration-500", !hasRun ? 'opacity-30' : 'opacity-100')}>
              {getStatusIcon('primary')}
              <div className="flex-1 pt-1">
                <h3 className="text-[11px] font-bold text-white mb-1 uppercase tracking-wider">1. Primary Synthesizer</h3>
                <p className="text-[10px] text-slate-500 leading-relaxed uppercase tracking-widest">Generates the initial creative solution based on the prompt.</p>
              </div>
            </div>

            {/* Step 2: Twin Agent */}
            <div className={cn("relative z-10 flex gap-4 transition-opacity duration-500", (!hasRun || status === 'primary') ? 'opacity-30' : 'opacity-100')}>
              {getStatusIcon('twin')}
              <div className="flex-1 pt-1">
                <h3 className="text-[11px] font-bold text-white mb-1 uppercase tracking-wider">2. Auditor Agent</h3>
                <p className="text-[10px] text-slate-500 leading-relaxed uppercase tracking-widest">Critiques, verifies, and optimizes the initial solution.</p>
              </div>
            </div>

            {/* Step 3: Final Output */}
            <div className={cn("relative z-10 flex gap-4 transition-opacity duration-500", (status !== 'completed') ? 'opacity-30' : 'opacity-100')}>
              {getStatusIcon('completed')}
              <div className="flex-1 pt-1">
                <h3 className="text-[11px] font-bold text-white mb-1 uppercase tracking-wider">3. Final Review</h3>
                <p className="text-[10px] text-slate-500 leading-relaxed uppercase tracking-widest">Consolidated and verified final output ready for use.</p>
              </div>
            </div>
          </div>
          
          {errorMsg && (
            <div className="mt-8 p-4 bg-red-900/10 border border-red-900/50 rounded-xl text-xs text-red-400">
              {errorMsg}
            </div>
          )}

        </div>
      </div>

      {/* RIGHT PANEL: Output Results */}
      <div className="flex-1 flex flex-col md:min-h-0 overflow-hidden relative glass m-4 md:m-6 md:ml-3 rounded-2xl z-10 border-white/20 md:h-[calc(100vh-3rem)]">

        {!hasRun ? (
          <div className="flex-1 flex flex-col items-center justify-center p-8 text-center h-full relative z-10">
            <div className="w-16 h-16 glass rounded-2xl flex items-center justify-center mb-6 shadow-2xl">
              <Bot size={24} className="text-blue-400" />
            </div>
            <h2 className="text-xl font-light tracking-[0.2em] uppercase text-white mb-3">Await Instruction</h2>
            <p className="text-xs text-slate-500 max-w-sm mx-auto leading-relaxed uppercase tracking-wider">
              Enter a prompt on the left to initiate the twin agent verification cycle. The results and process will appear here.
            </p>
          </div>
        ) : (
          <div className="flex flex-col h-full relative z-10">
            
            {/* Tabs */}
            <div className="flex items-center justify-between p-4 border-b border-white/10 glass sticky top-0 z-20">
              <div className="flex items-center gap-1">
                <button
                  onClick={() => setActiveTab('primary')}
                  className={cn(
                    "px-4 py-2 text-[10px] font-bold uppercase tracking-wider rounded-lg transition-all",
                    activeTab === 'primary' ? "bg-white/10 text-white" : "text-slate-500 hover:text-slate-300 hover:bg-white/5"
                  )}
                >
                  1. Initial Draft
                </button>
                <button
                  onClick={() => setActiveTab('critique')}
                  disabled={status === 'primary' && !critique}
                  className={cn(
                    "px-4 py-2 text-[10px] font-bold uppercase tracking-wider rounded-lg transition-all",
                    activeTab === 'critique' ? "bg-purple-500/20 text-purple-300 border border-purple-500/30" : "text-slate-500 hover:text-slate-300 hover:bg-white/5",
                    (status === 'primary' && !critique) && "opacity-30 cursor-not-allowed"
                  )}
                >
                  2. Verification & Critique
                </button>
                <button
                  onClick={() => setActiveTab('final')}
                  disabled={status !== 'completed' && !finalOutput}
                  className={cn(
                    "px-4 py-2 text-[10px] font-bold uppercase tracking-wider rounded-lg transition-all",
                    activeTab === 'final' ? "bg-blue-600 text-white" : "text-slate-500 hover:text-slate-300 hover:bg-white/5",
                    (status !== 'completed' && !finalOutput) && "opacity-30 cursor-not-allowed"
                  )}
                >
                  3. Final Output
                </button>
              </div>

              {status === 'completed' && (
                <button
                   onClick={replayEvolution}
                   disabled={isReplaying}
                   className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-lg border border-blue-500/30 text-blue-400 bg-blue-500/10 hover:bg-blue-500/20 transition-all text-[10px] font-bold uppercase tracking-widest disabled:opacity-50"
                 >
                   <Play size={12} className={cn(isReplaying && "animate-pulse")} />
                   {isReplaying ? "Replaying..." : "Replay History"}
                </button>
              )}
            </div>

            {/* Content Area */}
            <div className="flex-1 overflow-y-auto p-8 relative">
              <AnimatePresence mode="wait">
                {activeTab === 'primary' && (
                  <motion.div
                    key="primary"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.98 }}
                    transition={{ duration: 0.3 }}
                  >
                    {!primaryOutput && status === 'primary' ? (
                       <div className="flex items-center gap-3 text-blue-400 mt-4 text-[11px] font-mono tracking-widest uppercase">
                         <Loader2 className="animate-spin" size={14} /> Synthesizing draft... 
                       </div>
                    ) : (
                      <div className="glass rounded-3xl p-6 relative group border-blue-500/20">
                        <div className="absolute top-4 right-4 p-2 opacity-100 mb-6">
                           <span className="text-[8px] font-mono border border-blue-400/50 text-blue-400 px-2 py-1 rounded bg-blue-400/10">AGENT-ALPHA: CREATIVE</span>
                        </div>
                        <h3 className="text-sm font-semibold mb-4 text-blue-300 flex items-center gap-2">
                           <span className="w-1.5 h-1.5 rounded-full bg-blue-400"></span> Primary Synthesis
                        </h3>
                        <div className="markdown-body">
                          <ReactMarkdown>{primaryOutput}</ReactMarkdown>
                        </div>
                      </div>
                    )}
                  </motion.div>
                )}

                {activeTab === 'critique' && (
                  <motion.div
                    key="critique"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.98 }}
                    transition={{ duration: 0.3 }}
                  >
                    {!critique && status === 'twin' ? (
                       <div className="flex items-center gap-3 text-purple-400 mt-4 text-[11px] font-mono tracking-widest uppercase">
                         <Loader2 className="animate-spin" size={14} /> Cross-Examination in Progress...
                       </div>
                    ) : (
                      <div className="glass rounded-3xl p-6 relative group border-purple-500/20 shadow-[inset_0_0_30px_rgba(168,85,247,0.05)]">
                        <div className="absolute top-4 right-4 p-2 opacity-100 mb-6">
                           <span className="text-[8px] font-mono border border-purple-400/50 text-purple-400 px-2 py-1 rounded bg-purple-400/10">AGENT-BETA: AUDITOR</span>
                        </div>
                        <h3 className="text-sm font-semibold mb-4 text-purple-300 flex items-center gap-2">
                           <span className="w-1.5 h-1.5 rounded-full bg-purple-400"></span> Verification & Optimization
                        </h3>
                        <div className="markdown-body text-slate-300">
                          <ReactMarkdown>{critique}</ReactMarkdown>
                        </div>
                      </div>
                    )}
                  </motion.div>
                )}

                {activeTab === 'final' && (
                  <motion.div
                    key="final"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.98 }}
                    transition={{ duration: 0.3 }}
                  >
                    {!finalOutput && status !== 'completed' ? (
                       <div className="flex items-center gap-3 text-slate-500 mt-4 text-[11px] font-mono tracking-widest uppercase">
                         <Loader2 className="animate-spin" size={14} /> Waiting for validation phase...
                       </div>
                    ) : (
                       <div className="glass rounded-3xl p-6 relative group border-white/20 shadow-[inset_0_0_30px_rgba(255,255,255,0.05)]">
                          <h3 className="text-sm font-bold mb-4 text-white flex items-center gap-2">
                             <span className="w-3 h-3 rounded-full bg-blue-500 shadow-[0_0_10px_rgba(59,130,246,0.8)]"></span> Final Decision Output
                          </h3>
                          {generatedImageUrl && (
                            <div className="mb-6 rounded-xl overflow-hidden border border-white/10 shadow-lg">
                              <img src={generatedImageUrl} alt="Generated visual representation" referrerPolicy="no-referrer" className="w-full h-auto object-cover max-h-[400px]" />
                            </div>
                          )}
                          <div className="markdown-body">
                            <ReactMarkdown>{finalOutput}</ReactMarkdown>
                          </div>
                          <div className="mt-8 pt-4 border-t border-white/10 flex flex-col md:flex-row md:items-center justify-between gap-4">
                            <div className="text-[10px] text-slate-400 tracking-wider">
                              The twin agent verification cycle has completed.
                            </div>
                            <div className="flex items-center gap-2">
                              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mr-2">Share:</span>
                              <button onClick={() => handleShare('twitter')} className="w-8 h-8 rounded-full glass bg-white/5 flex items-center justify-center hover:bg-blue-400/20 hover:text-blue-400 hover:border-blue-400/50 transition-all text-slate-300" title="Share on Twitter/X">
                                <Twitter size={14} />
                              </button>
                              <button onClick={() => handleShare('facebook')} className="w-8 h-8 rounded-full glass bg-white/5 flex items-center justify-center hover:bg-blue-600/20 hover:text-blue-500 hover:border-blue-500/50 transition-all text-slate-300" title="Share on Facebook">
                                <Facebook size={14} />
                              </button>
                              <button onClick={() => handleShare('linkedin')} className="w-8 h-8 rounded-full glass bg-white/5 flex items-center justify-center hover:bg-blue-500/20 hover:text-blue-400 hover:border-blue-400/50 transition-all text-slate-300" title="Share on LinkedIn">
                                <Linkedin size={14} />
                              </button>
                              <button onClick={() => handleShare('whatsapp')} className="w-8 h-8 rounded-full glass bg-white/5 flex items-center justify-center hover:bg-green-500/20 hover:text-green-500 hover:border-green-500/50 transition-all text-slate-300" title="Share on WhatsApp">
                                <MessageCircle size={14} />
                              </button>
                              <button onClick={() => {
                                navigator.clipboard.writeText(finalOutput);
                              }} className="w-8 h-8 rounded-full glass bg-white/5 flex items-center justify-center hover:bg-white/20 hover:border-white/50 transition-all text-slate-300" title="Copy to clipboard">
                                <Copy size={14} />
                              </button>
                            </div>
                          </div>
                       </div>
                    )}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </div>
        )}
      </div>

    </div>
  );
}

